---
author: Lisa Hu
---
```{r include = FALSE}
# Copyright (c) 2022 Lisa Hu
# Licensed under GPLv3. See LICENSE
```
1. Public Health England (2021). Cancer survival in ENgland between 2014 and 2018. <https://www.gov.uk/government/statistics/cancer-survival-in-england-for-patients-diagnosed-between-2014-and-2018-and-followed-up-until-2019/cancer-survival-in-england-for-patients-diagnosed-between-2014-and-2018-and-followed-up-to-2019> \label{ref:england}
2. Ballehaninna, U., & Chamberlain, R. (2011). The clinical utility of serum CA 19-9 in the diagnosis, prognosis and management of pancreatic adenocarcinoma: An evidence based appraisal. *Journal Of Gastrointestinal Oncology, 3*(2), 105-119. <doi:10.3978/j.issn.2078-6891.2011.021> \label{ref:ca19}
3. Thongboonkerd, V. (2007), Recent progress in urinary proteomics. Prot. Clin. Appl., 1: 780-791. <https://doi.org/10.1002/prca.200700035> \label{ref:urine}
4. R Core Team (2022). R: A language and environment for statistical computing. R Foundation for
  Statistical Computing, Vienna, Austria. <https://www.R-project.org/> \label{ref:r}
5. Wickham H, Girlich M (2022). _tidyr: Tidy Messy Data_. R package version 1.2.1, <https://CRAN.R-project.org/package=tidyr> \label{ref:tidyr}
6. Wickham H, François R, Henry L, Müller K (2022). _dplyr: A Grammar of Data Manipulation_. R package version 1.0.10, <https://CRAN.R-project.org/package=dplyr> \label{ref:dplyr}
7. Daróczi G, Tsegelskyi R (2022). _pander: An R 'Pandoc' Writer_. R package version 0.6.5,<https://CRAN.R-project.org/package=pander> \label{ref:pander}
8. Wickham H, Hester J, Bryan J (2022). _readr: Read Rectangular Text Data_. R package version 2.1.3,<https://CRAN.R-project.org/package=readr> \label{ref:readr}
9. Ogle, D.H., J.C. Doll, P. Wheeler, and A. Dinno. 2022. FSA: Fisheries Stock Analysis. R package
  version 0.9.3, <https://github.com/fishR-Core-Team/FSA> \label{ref:fsa}
10. H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016. <https://ggplot2.tidyverse.org/> \label{ref:ggplot}
11. Kassambara A (2020). _ggpubr: 'ggplot2' Based Publication Ready Plots_. R package version 0.4.0,<https://CRAN.R-project.org/package=ggpubr> \label{ref:ggpubr}
12. Campitelli E (2022). _ggnewscale: Multiple Fill and Colour Scales in 'ggplot2'_. R package version 0.4.8, <https://CRAN.R-project.org/package=ggnewscale> \label{ref:scale}
13. Hornik K, Buchta C, Zeileis A (2009). “Open-Source Machine Learning: R Meets Weka.” _Computational
  Statistics_, *24*(2), 225-232. doi:10.1007/s00180-008-0119-7
  <https://doi.org/10.1007/s00180-008-0119-7> \label{ref:rweka}
14. Eibe Frank, Mark A. Hall, and Ian H. Witten (2016). The WEKA Workbench. Online Appendix for "Data Mining: Practical Machine Learning Tools and Techniques", Morgan Kaufmann, Fourth Edition, 2016. \label{ref:weka}
15. Eibe Frank (2013) thresholdSelector metaclassifier. <https://weka.sourceforge.io/doc.packages/thresholdSelector/weka/classifiers/meta/ThresholdSelector.html> \label{ref:ts}
